[ejs.landing]
updateAvailableTooltip = "¬°Actualizaci√≥n Disponible!"
usernamePlaceholder = "Nombre de Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Config"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "üî¥"
mojangStatus = "ESTADO"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ning√∫n Servidor Seleccionado"
launchDetails = "Por favor espera.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando Noticias.."
newsErrorFailedSpan = "Error al Cargar Noticias"
newsErrorRetryButton = "Intentar de Nuevo"
newsErrorNoneSpan = "Sin Noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "INICIAR SESI√ìN EN MINECRAFT"
loginEmailError = "* Valor Inv√°lido"
loginEmailPlaceholder = "CORREO ELECTR√ìNICO O NOMBRE DE USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASE√ëA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "¬øolvidaste la contrase√±a?"
loginRememberMeText = "¬ørecordar?"
loginButtonText = "INICIAR SESI√ìN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¬øNecesitas una Cuenta?"
loginPasswordDisclaimer1 = "Tu contrase√±a se env√≠a directamente a Mojang y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no est√° afiliado a Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de Inicio de Sesi√≥n"
loginWithMicrosoft = "Iniciar con Microsoft"
loginWithMojang = "Iniciar con Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una Cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuraciones"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Hecho"
tabAccountHeaderText = "Configuraciones de la Cuenta"
tabAccountHeaderDesc = "Agregar nuevas cuentas o gestionar las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar Cuenta de Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Agregar Cuenta de Mojang"
minecraftTabHeaderText = "Configuraciones de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resoluci√≥n del Juego"
launchFullscreenTitle = "Lanzar en pantalla completa."
autoConnectTitle = "Conectarse autom√°ticamente al servidor al iniciar."
launchDetachedTitle = "Lanzar el proceso del juego separado del launcher."
launchDetachedDesc = "Si el juego no est√° separado, cerrar el launcher tambi√©n cerrar√° el juego."
tabModsHeaderText = "Configuraciones de Mods"
tabModsHeaderDesc = "Habilitar o deshabilitar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods Obligatorios"
optionalMods = "Mods Opcionales"
dropinMods = "Mods Drag N Drop"
addMods = "Agregar Mods"
dropinRefreshNote = "(F5)"
shaderpacks = "Shaders"
shaderpackDesc = "Habilitar o deshabilitar shaders. Tenga en cuenta que los shaders solo funcionar√°n suavemente en configuraciones potentes. Puede agregar paquetes personalizados aqu√≠."
selectShaderpack = "Seleccionar Paquete de Shaders"
tabJavaHeaderText = "Configuraciones de Java"
tabJavaHeaderDesc = "Gestionar la configuraci√≥n de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM M√°xima"
minRAM = "RAM M√≠nima"
memoryDesc = "La RAM m√≠nima recomendada es de 3 gigabytes. Configurar los valores m√≠nimo y m√°ximo al mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar Ejecutable de Java"
javaExecSelButtonText = "Elegir Archivo"
javaExecDesc = "El ejecutable de Java se valida antes del lanzamiento del juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones Adicionales de JVM"
jvmOptsDesc = "Opciones para proporcionar a la JVM en tiempo de ejecuci√≥n. <em>-Xms</em> y <em>-Xmx</em> no deben incluirse."
launcherTabHeaderText = "Configuraciones del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el propio launcher."
allowPrereleaseTitle = "Permitir Actualizaciones de Pre-Lanzamiento."
allowPrereleaseDesc = "Las Pre-Lanzamientos incluyen nuevas funciones que pueden no haber sido completamente probadas o integradas.<br>Esto siempre ser√° verdadero si est√°s usando una versi√≥n de pre-lanzamiento."
dataDirectoryTitle = "Directorio de Datos"
selectDataDirectory = "Seleccionar Directorio de Datos"
chooseFolder = "Elegir Carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenar√°n en el directorio de datos.<br>Las capturas de pantalla y los guardados de mundo se almacenan en la carpeta de la instancia correspondiente a la configuraci√≥n del servidor."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver informaci√≥n y notas de la versi√≥n actual."
aboutTitle = "{appName}"
stableRelease = "Versi√≥n Estable"
versionText = "Versi√≥n "
sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de DevTools"
releaseNotes = "Notas de la Versi√≥n"
changelog = "Registro de Cambios"
noReleaseNotes = "Sin Notas de la Versi√≥n"
viewReleaseNotes = "Ver Notas de la Versi√≥n en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descargar, instalar y revisar actualizaciones para el launcher."
checkForUpdates = "Buscar Actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Notas de la Actualizaci√≥n"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Esperando al Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de Sesi√≥n de Microsoft"
microsoftLogoutTitle = "Cerrar Sesi√≥n de Microsoft"

[js.login]
login = "INICIAR SESI√ìN"
loggingIn = "INICIANDO SESI√ìN"
success = "√âXITO"
tryAgain = "Intentar de Nuevo"

[js.login.error]
invalidValue = "* Valor Inv√°lido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error Desconocido Durante el Inicio de Sesi√≥n"
desc = "Ocurri√≥ un error desconocido. Por favor, consulta la consola para m√°s detalles."

[js.landing.launch]
pleaseWait = "Por favor espera.."
failureTitle = "Error Durante el Lanzamiento"
failureText = "Consulta la consola (CTRL + Shift + i) para m√°s detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna Cuenta Seleccionada"

[js.landing.selectedServer]
noSelection = "Ning√∫n Servidor Seleccionado"
loading = "Cargando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "üî¥"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Comprobando informaci√≥n del sistema.."
noCompatibleJava = "No se Encontr√≥<br>Instalaci√≥n Compatible de Java"
installJavaMessage = "Para lanzar Minecraft, necesitas una instalaci√≥n de Java {major} de 64 bits. ¬øTe gustar√≠a que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Descarga de Java.."
javaDownloadFailureTitle = "Error Durante la Descarga de Java"
javaDownloadFailureText = "Consulta la consola (CTRL + Shift + i) para m√°s detalles."
javaRequired = "Se Requiere Java<br>para Lanzar"
javaRequiredMessage = 'Se necesita una instalaci√≥n v√°lida de Java {major} x64 para lanzar.<br><br>Por favor, consulta nuestra <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Gu√≠a de Gesti√≥n de Java</a> para instrucciones sobre c√≥mo instalar Java manualmente.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Regresar"

[js.landing.downloadJava]
findJdkFailure = "Failed to find OpenJDK distribution."
javaDownloadCorruptedError = "Downloaded JDK has a bad hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Fatal Error"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Preparing to launch.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Done. Enjoy the server!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "Loading game.."
joining = "Sailing to Westeros!"
joined = "Exploring the Realm!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft authentication failed. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft logout failed. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Select Account"
selectedButton = "Selected Account &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Warning<br>This is Your Last Account"
lastAccountWarningMessage = "In order to use the launcher you must be logged into at least one account. You will need to login again after.<br><br>Are you sure you want to log out?"
confirmButton = "I'm Sure"
cancelButton = "Cancel"

[js.settings.authAccountPopulate]
username = "Username"
uuid = "UUID"
selectAccount = "Select Account"
selectedAccount = "Selected Account ‚úì"
logout = "Log Out"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Main Server"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Invalid Selection"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "New Release Available"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Downloading.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "You Are Running the Latest Version"
checkForUpdatesButton = "Check for Updates"
checkingForUpdatesButton = "Checking for Updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Checking for Updates..."
installNowButton = "Install Now"
checkForUpdatesButton = "Check for Updates"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
